- incoming_path: "/3.0"
  route_type: "prefix"
  handler: "backend"
  backend_id: "fhapi-30"

- incoming_path: "/3.1"
  route_type: "prefix"
  handler: "backend"
  backend_id: "fhapi-31"

- incoming_path: "/3.2/test"
  route_type: "prefix"
  handler: "backend"
  backend_id: "fhapi-32"